# Generated by Django 5.2.1 on 2025-05-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grades',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
