# Generated by Django 5.2.1 on 2025-05-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_alter_customuser_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grades',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
