# Generated by Django 5.2.1 on 2025-05-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_alter_customuser_grades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='grades',
            new_name='age',
        ),
    ]
